### PR TITLE
textures: use sloth-aliases.txt feature

### PR DESCRIPTION
**Pull request by illwieckz**
- Deduplicate normal and specular maps with the `tex-ex` package.
- Reuse height maps from the `tex-ex` package.

This requires a Sloth tool with the `sloth-alias.txt` feature:

- https://github.com/DaemonEngine/Sloth/pull/11

### CODE REVIEW

**Comment by slipher** [comment]
If `tex-ex` heightmaps have a custom depth scale in the future, how will this work?

**Comment by illwieckz** [comment]
That's a very good question. Given the alias is meant to provide image basenames that are missing from the current directory, we may read a configuration file for such image basename from the current directory even if the image is missing, this would require to duplicate such configuration file for every alias, but because of those being configuration files, this would not contribute to the final package.

**Comment by illwieckz** [comment]
I think I will rename the alias file `sloth-alias.txt` and make a precedent for this kind of naming scheme, for relief mapping we can do `sloth-relief.txt` (with `image_name option1 option2 option3` lines), etc.

**Comment by slipher** [comment]
I think the idea of having dependencies between the texture packages is questionable and needs more consideration.

**Comment by illwieckz** [comment]
The `exm` package is meant to be an extension to `ex`, so it makes sense to depend on it.

**Comment by slipher** [comment]
If there's going to be a dependency it should at least be versioned. If there is an unversioned dependency, you could end up with different versions that don't work together.

**Comment by illwieckz** [comment]
This problem happens with every package that has a deps. I don't want to postpone this for an Urcheon feature request like that. Also the `tex-ex` dependency is very stable and has not been modified. So, I see no urge to worry about a mismatch that is not happening. Also, modification to `tex-ex` that are not bugfixes or things like that but that are actually modifying textures are meant to happen in `tex-exm`, which is expected to remove almost all causes of mismatch: texture file paths from `tex-ex` are not supposed to be modified anymore.

**Pull request merged**
