### PR TITLE
add heightmaps

### PR DESCRIPTION
**Pull request by sweet235**
convert the normalmaps to heightmaps using
https://gitlab.com/xonotic/xonotic/-/blob/master/misc/tools/fft-normalmap-to-heightmap.c

this works quite well, except for some nuts/bolts
link to the heightmaps without these features until we do this by hand

can image files cause incorrect rendering with old engine versions?

### CODE REVIEW

**Review by DolceTriade — APPROVED** [review]

**Comment by sweet235** [comment]
Map parpax before:
unvanquished_2024-09-08_203839_000

After:
unvanquished_2024-09-08_203909_000

**Comment by slipher** [comment]
The grate looks wonky. The horizontal parts seem to be bulging out

**Comment by sweet235** [comment]
> The grate looks wonky. The horizontal parts seem to be bulging out

Probably because of the filtering in the X and Y directions in the frequency spectrum. One has to do this, as many normal maps are inconsistent. That is: they do not sum to the same heights in all directions.

The little black holes are not quadratic. So the height signal's frequency is different in X and Y direction. I would have to adjust the filter characteristics by hand.

Or maybe that is just the engine's own filtering.

**Comment by mjstahlberg** [comment]
> The grate looks wonky. The horizontal parts seem to be bulging out

I agree that the result doesn't look better, though that in itself may be due to aggressive/bad parallax mapping making use of these maps. (The floor also looks noisy in both before and after images due to parallax.) In addition to the bulging, the texture even appears to be shifted upwards with some parts from the "next ventilation element" unintendedly showing.

I'm also not convinced of the converted maps as such (i.e., regardless of the resulting looks). Most notably,

- the upper and lower bevels of [textures/shared_exm_src/trim_16x04v2_h.png](https://github.com/UnvanquishedAssets/tex-exm_src.dpkdir/pull/1/files#diff-104bbb491ac096f4a9c83d08270b3259be2dea48aadc94eb6eec6cde8fe61d06) do not match [textures/shared_exm_src/trim_16x04v1_h.png](https://github.com/UnvanquishedAssets/tex-exm_src.dpkdir/pull/1/files#diff-0afe26a442d95d89035f43a8b47c10cdb7beb0aebabbe3483e18bb26e5e929d0). The two textures are frequently used together and need to fit.
- The ventilation elements of [textures/shared_exm_src/trim_16x08v2_h.png](https://github.com/UnvanquishedAssets/tex-exm_src.dpkdir/pull/1/files#diff-f7036588a55283766ceac81bec55f2b9f9fc9c295730b542cee18d2b9458be84) are flying.
- The part left and right of the black stripes in [textures/shared_exm_src/trim_16x08v4_h.png](https://github.com/UnvanquishedAssets/tex-exm_src.dpkdir/pull/1/files#diff-3856d699addf10b1c78e0c6ee5c63efdceea3071e9dfbb296939eb98e9858ad8) are higher than the surrounding flat panel, so they would bulge out while the should be flat. I'm also not sure if the black stripes should be full black. (Are these really holes?)
- [textures/shared_exm_src/trim_16x08v6_h.png](https://github.com/UnvanquishedAssets/tex-exm_src.dpkdir/pull/1/files#diff-be29bc76bdce9f7999ce6b97eb8c4faff4c03c961fab87cd564b2f2c42f366db) also has artifacts around the nuts were the height varies based on the angle.

So I think regardless of whether one prefers before or after, the heightmaps are not encoding the height properly.

**Comment by sweet235** [comment]
> the heightmaps are not encoding the height properly

Neither are the existing normalmaps.

**Comment by sweet235** [comment]
I will continue this effort at https://github.com/InterstellarOasis/tex-exms_src.dpkdir

**Comment by illwieckz** [comment]
We probably already have heightmaps for them. The `exm` package is a modification of the `ex` one, so most textures probably already have a heightmap in the `ex` package.

**Comment by illwieckz** [comment]
For example:

https://github.com/UnvanquishedAssets/tex-ex_src.dpkdir/blob/master/textures/shared_ex_src/floor_grate1_h.png

If you want to generate heightmaps we don't have yet, you better focus on `ej01` and `vega` (beware that the normal format in vega textures is very exotic).

**Comment by illwieckz** [comment]
Also the `tech` one is missing height maps.

**Comment by sweet235** [comment]
> For example:
>
> https://github.com/UnvanquishedAssets/tex-ex_src.dpkdir/blob/master/textures/shared_ex_src/floor_grate1_h.png

This one should fit. But none of the trim textures has a suitable replacement there.

> better focus on ej01 and vega

> Also the tech one

Indeed. But the ex(m) textures are used more widely in contributed maps. But to be honest, my motivation is kind of selfish, because I used them in one of my own maps. The exm materials in particular have rather neutral trims, which fit a wide variety of styles.

**Comment by slipher** [comment]
> > The grate looks wonky. The horizontal parts seem to be bulging out
> 
> Probably because of the filtering in the X and Y directions in the frequency spectrum. One has to do this, as many normal maps are inconsistent. That is: they do not sum to the same heights in all directions.
> 
> The little black holes are not quadratic. So the height signal's frequency is different in X and Y direction. I would have to adjust the filter characteristics by hand.

@sweet235 Thanks for the explanation. I checked some numeric values of `trim_16x08v2_h.png` (which you said is shown in the screenshot) along a vertical bar and found that at the intersection points it is higher by about 20 on a 0-255 scale. So the engine is correctly displaying what it is given, as far as I can tell. I'm not saying this must be fixed before merging; mostly I wanted to check that the engine and the texture and shader generation processes are not buggy. It's fine if there are some imperfections.

> We probably already have heightmaps for them. The `exm` package is a modification of the `ex` one, so most textures probably already have a heightmap in the `ex` package.

> For example:
> 
> https://github.com/UnvanquishedAssets/tex-ex_src.dpkdir/blob/master/textures/shared_ex_src/floor_grate1_h.png
> 
> If you want to generate heightmaps we don't have yet, you better focus on `ej01` and `vega` (beware that the normal format in vega textures is very exotic).

@illwieckz What exactly do you mean to suggest by this? That we should try to copy and paste height maps from `tex-ex` where possible? Or that mappers who want to have height maps should avoid `tex-exm` and use `tex-ex` instead?

**Comment by illwieckz** [comment]
We can either copy the heightmaps there, but I have a better solution:

- https://github.com/UnvanquishedAssets/tex-exm_src.dpkdir/pull/2

This would make tex-exm load the ex heightmaps without any duplication, neither in repositories, neither in packages, neither in game / gpu memory.

As a remind, the actual ex heightmaps were derivated from the ones Xonotic generated for themselves using the same script Sweet is using, so they are already affected by some glitches. _Edit:_ but they may have done touch-ups.

**Comment by mjstahlberg** [comment]
> As a remind, the actual ex heightmaps were derivated from the ones Xonotic generated for themselves using the same script Sweet is using, so they are already affected by some glitches. _Edit:_ but they may have done touch-ups.

The Xonotic-generated heightmaps for _ex_ are different at least in the sense that they have less contrast, but some of them are also _horribly_ wrong. To give just one example:

image

image

image

Note that the normal map looks fine but the height map is actively and massively degrading the quality of the shader.

Some (though not all) of the heightmaps imported from Xonotic are so bad that I doubt they were even converted by the same script that was used here, which has produced somewhat milder bulging artifacts.

**Comment by sweet235** [comment]
> Thanks for the explanation

My story sounds educated, but might be kind of wrong, because `floor_grate1_h` should be affected in a similar way. Maybe the frequencies get messed up by the stripes of constant height at the top and bottom. I also did a Gaussian blur with 2x2 pixels size, that might be (part of) the reason as well.

> normal map looks fine but the height map is actively and massively degrading the quality of the shader

I left out these nuts/bolts on purpose, except in one case where their relative height is almost zero. The reason is that the Xonotic normal map integrator seems to get this wrong:

trim_16x04v3_d
trim_16x04v3_n
trim_16x04v3_h

The last image is its raw output. Notice how the height is too low left of the nuts/bolts, the program fails here. This is a rather sophisticated program, it does quite well in fixing normalmap inconsistencies in most cases I tried. I tried to tweak the modifications it does to the spectrum, but so far without success.

I suspect that someone working on the Xonotic assets encountered the same problem, and went for the solution above.

Why are we using the Xonotic normal map integrator? This is what I get if I sum the horizontal signal naively (might be incorrect):

foo

Notice how the slight inconsistencies sum up to dominate the height.

@Masmblr drew this detail by hand. This is not perfect either, but much better. So I figured we might do just that:

trim_16x04v3_h_matth

**Pull request closed without merging**
